# SPDX-License-Identifier: PMPL-1.0-or-later
# Rustfmt configuration for Protocol Squisher
# Only stable options â€” nightly-only options are excluded to keep CI green.

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
match_block_trailing_comma = true
remove_nested_parens = true
